# Generated by Django 4.0 on 2022-03-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinations_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='submit_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('specialist', models.CharField(blank=True, max_length=20, null=True)),
                ('examinations_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='summary_of_results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('start_month', models.IntegerField(blank=True, default=0, null=True)),
                ('start_year', models.IntegerField(blank=True, default=0, null=True)),
                ('job', models.CharField(blank=True, max_length=30, null=True)),
                ('examinations_code', models.CharField(blank=True, max_length=20, null=True)),
                ('job_code', models.CharField(blank=True, max_length=30, null=True)),
                ('gender', models.CharField(blank=True, choices=[('mard', 'مرد'), ('zan', 'زن')], default='mard', max_length=20, null=True)),
                ('harmful_factors', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], default=1, null=True)),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('length', models.IntegerField(blank=True, default=0, null=True)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('body_mass', models.CharField(blank=True, max_length=300, null=True)),
                ('body_mass_status', models.CharField(blank=True, max_length=300, null=True)),
                ('blood_sugar', models.IntegerField(blank=True, default=0, null=True)),
                ('blood_sugar_status', models.CharField(blank=True, max_length=300, null=True)),
                ('blood_pressure', models.IntegerField(blank=True, default=0, null=True)),
                ('blood_pressure_status', models.CharField(blank=True, max_length=300, null=True)),
                ('cholesterol', models.IntegerField(blank=True, default=0, null=True)),
                ('cholesterol_status', models.CharField(blank=True, max_length=300, null=True)),
                ('triglyceride', models.IntegerField(blank=True, default=0, null=True)),
                ('triglyceride_status', models.CharField(blank=True, max_length=300, null=True)),
                ('urine', models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('not_normal', 'غیر نرمال'), ('none', 'ندارد')], default='', max_length=300, null=True)),
                ('breathing_test', models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('tahdidi', 'تحدیدی'), ('ensedadi', 'انسدادی'), ('try', 'نیاز به تکرار'), ('namaie_toaman', 'نمای توامان تحدیدی وانسدادی'), ('none', 'ندارد')], default='null', max_length=300, null=True)),
                ('left_ear_hearing', models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('kahesh_shenavai_hedayati', 'کاهش شنوایی هدایتی'), ('kahesh_shenavai_hesi_asabi', 'کاهش شنوایی حسی عصبی'), ('kahesh_shenavai_nashi-az-seda', 'کاهش شنوایی ناشی از صدا'), ('toaman_hedayati_va_hesi-asabi', 'توامان هدایتی و حسی عصبی'), ('none', 'ندارد')], default='', max_length=300, null=True)),
                ('right_ear_hearing', models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('kahesh_shenavai_hedayati', 'کاهش شنوایی هدایتی'), ('kahesh_shenavai_hesi_asabi', 'کاهش شنوایی حسی عصبی'), ('kahesh_shenavai_nashi-az-seda', 'کاهش شنوایی ناشی از صدا'), ('toaman_hedayati_va_hesi-asabi', 'توامان هدایتی و حسی عصبی'), ('none', 'ندارد')], default='', max_length=300, null=True)),
                ('left_eye_vision', models.IntegerField(blank=True, default=0, null=True)),
                ('left_eye_vision_status', models.CharField(blank=True, max_length=300, null=True)),
                ('left_eye_vision_with_glasses', models.IntegerField(blank=True, default=0, null=True)),
                ('right_eye_vision', models.IntegerField(blank=True, default=0, null=True)),
                ('right_eye_vision_status', models.CharField(blank=True, max_length=300, null=True)),
                ('right_eye_vision_with_glasses', models.IntegerField(blank=True, default=0, null=True)),
                ('color_vision', models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('not_normal', 'غیر نرمال'), ('tashkhis_rang_ghermez', 'تشخیص رنگ قرمز'), ('none', 'ندارد')], default='', max_length=300, null=True)),
                ('field_of_veiw', models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('not_normal', 'غیر نرمال'), ('none', 'ندارد')], default='', max_length=300, null=True)),
                ('depth_vision', models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('not_normal', 'غیر نرمال'), ('none', 'ندارد')], default='', max_length=300, null=True)),
                ('breast_photo', models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('not_normal', 'غیر نرمال'), ('none', 'ندارد')], default='', max_length=300, null=True)),
                ('heart', models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('taghirat_gheir_ekhtesasi', 'تغییرات غیر اختصاصی'), ('try', 'نیاز به تکرار'), ('not_normal', 'غیر نرمال'), ('none', 'ندارد')], default='', max_length=300, null=True)),
                ('blood_lead', models.IntegerField(blank=True, default=0, null=True)),
                ('blood_lead_status', models.CharField(blank=True, max_length=300, null=True)),
                ('chratinin', models.IntegerField(blank=True, default=0, null=True)),
                ('PSA', models.IntegerField(blank=True, default=0, null=True)),
                ('PSA_status', models.CharField(blank=True, max_length=300, null=True)),
                ('D3', models.IntegerField(blank=True, default=0, null=True)),
                ('TSH', models.IntegerField(blank=True, default=0, null=True)),
                ('TSH_status', models.CharField(blank=True, max_length=300, null=True)),
                ('problem', models.CharField(blank=True, max_length=300, null=True)),
                ('problems_with_the_persons_job', models.CharField(blank=True, choices=[('null', ''), ('darad', 'دارد'), ('none', 'ندارد')], default='', max_length=300, null=True)),
                ('recommendations', models.CharField(blank=True, max_length=300, null=True)),
                ('refer_to_specialist', models.CharField(blank=True, choices=[('null', ''), ('none', 'ندارد'), ('ghalb_orogh', 'قلب و عروق'), ('dakheli', 'داخلی'), ('rie', 'ریه'), ('ghodad', 'غدد'), ('saier', 'سایر')], default='', max_length=300, null=True)),
                ('final_theory', models.CharField(blank=True, choices=[('null', ''), ('belamane', 'بلامانع'), ('taghir_shekl', 'تغییر شغل'), ('mashrot', 'مشروط'), ('comision', 'کمیسیون')], default='', max_length=300, null=True)),
                ('reson_for_opening_the_case', models.CharField(blank=True, max_length=300, null=True)),
                ('occupational_actions', models.CharField(blank=True, choices=[('null', ''), ('darhal_peygiri', 'درحال پیگیری'), ('done', 'انجام شده'), ('not_done', 'انجام نشده')], default='', max_length=300, null=True)),
                ('occupational_disease_code', models.CharField(blank=True, max_length=300, null=True)),
                ('AST', models.IntegerField(blank=True, default=0, null=True)),
                ('AST_status', models.CharField(blank=True, max_length=300, null=True)),
                ('ALT', models.IntegerField(blank=True, default=0, null=True)),
                ('ALT_status', models.CharField(blank=True, max_length=300, null=True)),
                ('age_two', models.IntegerField(blank=True, default=0, null=True)),
                ('duration_of_employment', models.CharField(blank=True, max_length=300, null=True)),
                ('overweight', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
