# Generated by Django 4.0 on 2022-03-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0002_order_alter_summary_of_results_alt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_number',
        ),
    ]
