# Generated by Django 4.0 on 2022-04-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0007_personal_species_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_job', models.CharField(blank=True, max_length=50, null=True)),
                ('current_job_duty', models.CharField(blank=True, max_length=50, null=True)),
                ('current_job_from', models.CharField(blank=True, max_length=50, null=True)),
                ('current_job_to', models.CharField(blank=True, max_length=50, null=True)),
                ('current_job_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('second_current_job', models.CharField(blank=True, max_length=50, null=True)),
                ('second_current_job_duty', models.CharField(blank=True, max_length=50, null=True)),
                ('second_current_job_from', models.CharField(blank=True, max_length=50, null=True)),
                ('second_current_job_to', models.CharField(blank=True, max_length=50, null=True)),
                ('second_current_job_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_job', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_job_duty', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_job_from', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_job_to', models.CharField(blank=True, max_length=50, null=True)),
                ('previous_job_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('second_previous_job', models.CharField(blank=True, max_length=50, null=True)),
                ('second_previous_job_duty', models.CharField(blank=True, max_length=50, null=True)),
                ('second_previous_job_from', models.CharField(blank=True, max_length=50, null=True)),
                ('second_previous_job_to', models.CharField(blank=True, max_length=50, null=True)),
                ('second_previous_job_reason', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='personal_species',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
