# Generated by Django 4.0 on 2022-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0008_job_history_personal_species_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_ph_noise', models.BooleanField(default=False)),
                ('current_ph_erteash', models.BooleanField(default=False)),
                ('current_ph_not_unizan', models.BooleanField(default=False)),
                ('current_ph_unizan', models.BooleanField(default=False)),
                ('current_ph_stress', models.BooleanField(default=False)),
                ('current_ph_other', models.BooleanField(default=False)),
                ('current_sh_dust', models.BooleanField(default=False)),
                ('current_sh_metals', models.BooleanField(default=False)),
                ('current_sh_halal', models.BooleanField(default=False)),
                ('current_sh_afat', models.BooleanField(default=False)),
                ('current_sh_asidvbaz', models.BooleanField(default=False)),
                ('current_sh_gaz', models.BooleanField(default=False)),
                ('current_bio_gazesh', models.BooleanField(default=False)),
                ('current_bio_bactery', models.BooleanField(default=False)),
                ('current_bio_virus', models.BooleanField(default=False)),
                ('current_bio_angal', models.BooleanField(default=False)),
                ('current_bio_other', models.BooleanField(default=False)),
                ('current_er_standvsit', models.BooleanField(default=False)),
                ('current_er_loop', models.BooleanField(default=False)),
                ('current_er_hamlvnaghl', models.BooleanField(default=False)),
                ('current_er_vaziat_namonaseb', models.BooleanField(default=False)),
                ('current_er_other', models.BooleanField(default=False)),
                ('current_rav_order', models.BooleanField(default=False)),
                ('current_rav_stressor', models.BooleanField(default=False)),
                ('current_rav_other', models.BooleanField(default=False)),
                ('previous_ph_noise', models.BooleanField(default=False)),
                ('previous_ph_erteash', models.BooleanField(default=False)),
                ('previous_ph_not_unizan', models.BooleanField(default=False)),
                ('previous_ph_unizan', models.BooleanField(default=False)),
                ('previous_ph_stress', models.BooleanField(default=False)),
                ('previous_ph_other', models.BooleanField(default=False)),
                ('previous_sh_dust', models.BooleanField(default=False)),
                ('previous_sh_metals', models.BooleanField(default=False)),
                ('previous_sh_halal', models.BooleanField(default=False)),
                ('previous_sh_afat', models.BooleanField(default=False)),
                ('previous_sh_asidvbaz', models.BooleanField(default=False)),
                ('previous_sh_gaz', models.BooleanField(default=False)),
                ('previous_bio_gazesh', models.BooleanField(default=False)),
                ('previous_bio_bactery', models.BooleanField(default=False)),
                ('previous_bio_virus', models.BooleanField(default=False)),
                ('previous_bio_angal', models.BooleanField(default=False)),
                ('previous_bio_other', models.BooleanField(default=False)),
                ('previous_er_standvsit', models.BooleanField(default=False)),
                ('previous_er_loop', models.BooleanField(default=False)),
                ('previous_er_hamlvnaghl', models.BooleanField(default=False)),
                ('previous_er_vaziat_namonaseb', models.BooleanField(default=False)),
                ('previous_er_other', models.BooleanField(default=False)),
                ('previous_rav_order', models.BooleanField(default=False)),
                ('previous_rav_stressor', models.BooleanField(default=False)),
                ('previous_rav_other', models.BooleanField(default=False)),
            ],
        ),
    ]
