# Generated by Django 4.0 on 2022-02-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0009_summary_of_results_examinations_code_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='submit_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=20, null=True)),
                ('doctor', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('specialist', models.CharField(blank=True, max_length=20, null=True)),
                ('examinations_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='summary_of_results',
            old_name='examinations_code_form',
            new_name='examinations_code',
        ),
    ]
