# Generated by Django 4.0 on 2022-04-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0009_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_y', models.BooleanField(default=False)),
                ('first_n', models.BooleanField(default=False)),
                ('first_des', models.CharField(blank=True, max_length=50, null=True)),
                ('second_y', models.BooleanField(default=False)),
                ('second_n', models.BooleanField(default=False)),
                ('second_des', models.CharField(blank=True, max_length=50, null=True)),
                ('third_y', models.BooleanField(default=False)),
                ('third_n', models.BooleanField(default=False)),
                ('third_des', models.CharField(blank=True, max_length=50, null=True)),
                ('fourth_y', models.BooleanField(default=False)),
                ('fourth_n', models.BooleanField(default=False)),
                ('fourth_des', models.CharField(blank=True, max_length=50, null=True)),
                ('fifth_y', models.BooleanField(default=False)),
                ('fifth_n', models.BooleanField(default=False)),
                ('fifth_des', models.CharField(blank=True, max_length=50, null=True)),
                ('sixth_y', models.BooleanField(default=False)),
                ('sixth_n', models.BooleanField(default=False)),
                ('sixth_des', models.CharField(blank=True, max_length=50, null=True)),
                ('seventh_y', models.BooleanField(default=False)),
                ('seventh_n', models.BooleanField(default=False)),
                ('seventh_des', models.CharField(blank=True, max_length=50, null=True)),
                ('eighth_y', models.BooleanField(default=False)),
                ('eighth_n', models.BooleanField(default=False)),
                ('eighth_des', models.CharField(blank=True, max_length=50, null=True)),
                ('ninth_y', models.BooleanField(default=False)),
                ('ninth_n', models.BooleanField(default=False)),
                ('ninth_des', models.CharField(blank=True, max_length=50, null=True)),
                ('tenth_y', models.BooleanField(default=False)),
                ('tenth_n', models.BooleanField(default=False)),
                ('tenth_des_number', models.CharField(blank=True, max_length=50, null=True)),
                ('tenth_des_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('eleventh_y', models.BooleanField(default=False)),
                ('eleventh_n', models.BooleanField(default=False)),
                ('eleventh_des_number', models.CharField(blank=True, max_length=50, null=True)),
                ('eleventh_des_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('twelfth_y', models.BooleanField(default=False)),
                ('twelfth_n', models.BooleanField(default=False)),
                ('twelfth_des', models.CharField(blank=True, max_length=50, null=True)),
                ('thirteenth_y', models.BooleanField(default=False)),
                ('thirteenth_n', models.BooleanField(default=False)),
                ('thirteenth_des_type', models.CharField(blank=True, max_length=50, null=True)),
                ('thirteenth_des_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('fourteenth_y', models.BooleanField(default=False)),
                ('fourteenth_n', models.BooleanField(default=False)),
                ('fourteenth_des', models.CharField(blank=True, max_length=50, null=True)),
                ('fifteenth_y', models.BooleanField(default=False)),
                ('fifteenth_n', models.BooleanField(default=False)),
                ('fifteenth_des', models.CharField(blank=True, max_length=50, null=True)),
                ('sixteenth_y', models.BooleanField(default=False)),
                ('sixteenth_n', models.BooleanField(default=False)),
                ('sixteenth_des', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='date_day',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='date_month',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='date_year',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='kar_shenas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='kar_shenas_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='required_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
