# Generated by Django 4.0 on 2022-04-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0010_personal_history_assessment_date_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinations_code', models.CharField(blank=True, max_length=20, null=True)),
                ('order_number', models.IntegerField(blank=True, choices=[(1, '1'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50')], default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Examinations_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_year', models.IntegerField(blank=True, default=0, null=True)),
                ('date_month', models.IntegerField(blank=True, default=0, null=True)),
                ('date_day', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Assessment',
            new_name='Assessment_Model',
        ),
        migrations.RenameModel(
            old_name='Job_History',
            new_name='Job_History_Model',
        ),
        migrations.RenameModel(
            old_name='Personal_History',
            new_name='Personal_History_Model',
        ),
        migrations.RenameModel(
            old_name='Personal_Species',
            new_name='Personal_Species_Model',
        ),
        migrations.RenameModel(
            old_name='submit_company',
            new_name='Submit_Company_Model',
        ),
        migrations.RenameModel(
            old_name='summary_of_results',
            new_name='Summary_Of_Results_Model',
        ),
        migrations.DeleteModel(
            name='disease',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
