# Generated by Django 4.0 on 2022-02-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0010_submit_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examinations_code', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
