# Generated by Django 4.0 on 2022-04-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0013_consulting_experiments_final_theory_para_clinic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consulting',
            new_name='Consulting_Model',
        ),
        migrations.RenameModel(
            old_name='Experiments',
            new_name='Experiments_Model',
        ),
        migrations.RenameModel(
            old_name='Final_Theory',
            new_name='Final_Theory_Model',
        ),
        migrations.RenameModel(
            old_name='Para_Clinic',
            new_name='Para_Clinic_Model',
        ),
    ]
