# Generated by Django 4.0 on 2022-03-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0014_alter_summary_of_results_breast_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinations',
            old_name='audio_null',
            new_name='doctor_change',
        ),
        migrations.RenameField(
            model_name='examinations',
            old_name='doctor_not_normal',
            new_name='doctor_comision',
        ),
        migrations.RenameField(
            model_name='examinations',
            old_name='doctor_null',
            new_name='doctor_condition',
        ),
        migrations.RenameField(
            model_name='examinations',
            old_name='espiro_null',
            new_name='examinations_code',
        ),
        migrations.RenameField(
            model_name='examinations',
            old_name='opto_null',
            new_name='specialist_done',
        ),
        migrations.RenameField(
            model_name='examinations',
            old_name='specialist_normal',
            new_name='specialist_invest',
        ),
        migrations.RenameField(
            model_name='examinations',
            old_name='specialist_not_normal',
            new_name='specialist_need',
        ),
        migrations.RenameField(
            model_name='examinations',
            old_name='specialist_null',
            new_name='specialist_no_need',
        ),
        migrations.RenameField(
            model_name='examinations',
            old_name='test_null',
            new_name='specialist_not_done',
        ),
        migrations.AlterField(
            model_name='summary_of_results',
            name='breathing_test',
            field=models.CharField(blank=True, choices=[('null', ''), ('normal', 'نرمال'), ('tahdidi', 'تحدیدی'), ('ensedadi', 'انسدادی'), ('try', 'نیاز به تکرار'), ('namaie_toaman', 'نمای توامان تحدیدی وانسدادی'), ('none', 'ندارد')], default='null', max_length=300, null=True),
        ),
    ]
