# Generated by Django 4.0 on 2022-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0014_rename_consulting_consulting_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_species_model',
            name='raste',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
