# Generated by Django 4.0 on 2022-03-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0015_rename_audio_null_examinations_doctor_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinations',
            name='age',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examinations',
            name='harmful',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examinations',
            name='job',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='examinations',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
