# Generated by Django 4.0 on 2022-03-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0016_examinations_age_examinations_harmful_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='examinations',
        ),
    ]
