# Generated by Django 4.0 on 2022-04-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0019_alter_assessment_model_kar_shenas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinations_model',
            name='code',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3')], default=1, null=True),
        ),
    ]
