# Generated by Django 4.0 on 2022-04-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0020_examinations_model_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_theory_model',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
