# Generated by Django 4.2 on 2023-04-12 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0053_alter_examinations_model_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_species_model',
            name='marriage_status',
            field=models.CharField(blank=True, choices=[('mojarad', 'مجرد'), ('motahel', 'متاهل')], default='mojarad', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='personal_species_model',
            name='personal_code',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
