# Generated by Django 4.2 on 2023-04-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0054_alter_personal_species_model_marriage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_species_model',
            name='children',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
