# Generated by Django 4.2 on 2023-04-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0055_alter_personal_species_model_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_species_model',
            name='personal_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
