# Generated by Django 4.2 on 2023-05-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0056_alter_personal_species_model_personal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationscourse',
            name='CompanyName',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='examinationscourse',
            name='examinations_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
