# Generated by Django 4.2 on 2023-05-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0059_rename_blood_pressure_examinations_model_blood_pressure_bot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_theory_model',
            name='final_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final_theory_model',
            name='final_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final_theory_model',
            name='final_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
