# Generated by Django 4.2 on 2023-05-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0060_final_theory_model_final_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='para_clinic_model',
            old_name='opto_rangi',
            new_name='opto_rangi_l',
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_rangi_r',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=250, null=True),
        ),
    ]
