# Generated by Django 4.2 on 2023-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsianapp', '0061_rename_opto_rangi_para_clinic_model_opto_rangi_l_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='para_clinic_model',
            old_name='opto_meidan',
            new_name='opto_meidan_l',
        ),
        migrations.AddField(
            model_name='para_clinic_model',
            name='opto_meidan_r',
            field=models.CharField(blank=True, choices=[('normal', 'نرمال'), ('not_normal', 'غیر نرمال')], max_length=250, null=True),
        ),
    ]
