from django.db import models
from django import forms

class summary_of_results(models.Model):
    name = models.CharField(max_length=20)
    start_month = models.IntegerField(default=0)
    start_year = models.IntegerField(default=0)
    job = models.CharField(max_length=30)
    harmful_factors = models.CharField(max_length=100)
    CODE_CHOICES=[('1'),('2'),('3')]
    code = forms.ChoiceField(choices=CODE_CHOICES, widget=forms.RadioSelect)
    age = models.IntegerField(default=0)
    length = models.IntegerField(default=0)
    weight = models.IntegerField(default=0)
    body_mass = models.CharField(max_length=300)
    body_mass_status = models.CharField(max_length=300)
    blood_sugar = models.IntegerField(default=0)
    blood_sugar_status = models.CharField(max_length=300)
    blood_pressure = models.IntegerField(default=0)
    blood_pressure_status = models.CharField(max_length=300)
    cholesterol = models.IntegerField(default=0)
    cholesterol_status = models.CharField(max_length=300)
    triglyceride = models.IntegerField(default=0)
    triglyceride_status = models.CharField(max_length=300)
    urine_CHOICES=[('نرمال'),('غیر نرمال'),('ندارد')]
    urine = forms.ChoiceField(choices=urine_CHOICES, widget=forms.RadioSelect)
    breath_CHOICES=[('نرمال'),('تحدیدی'),('انسدادی'),('نیاز به تکرار'),('نمای توامان تحدیدی وانسدادی'),('ندارد'),]
    breathing_test = forms.ChoiceField(choices=breath_CHOICES, widget=forms.RadioSelect)
    left_ear_hearing = models.CharField(max_length=300)
    right_ear_hearing = models.CharField(max_length=300)
    left_eye_vision = models.CharField(max_length=300)
    left_eye_vision_status = models.CharField(max_length=300)
    left_eye_vision_with_glasses = models.CharField(max_length=300)
    right_eye_vision = models.CharField(max_length=300)
    right_eye_vision_status = models.CharField(max_length=300)
    right_eye_vision_with_glasses = models.CharField(max_length=300)
    color_vision = models.CharField(max_length=300)
    field_of_veiw = models.CharField(max_length=300)
    depth_vision_status = models.CharField(max_length=300)
    breast_photo = models.CharField(max_length=300)
    blood_lead = models.CharField(max_length=300)
    blood_lead_status = models.CharField(max_length=300)
    PSA = models.CharField(max_length=300)
    PSA_status = models.CharField(max_length=300)
    TSH = models.CharField(max_length=300)
    TSH_status = models.CharField(max_length=300)
    problem = models.CharField(max_length=300)
    problems_with_the_persons_job = models.CharField(max_length=300)
    recommendations = models.CharField(max_length=300)
    refer_to_specialist = models.CharField(max_length=300)
    final_theory = models.CharField(max_length=300)
    reson_for_opening_the_case = models.CharField(max_length=300)
    occupational_actions = models.CharField(max_length=300)
    occupational_disease_code = models.CharField(max_length=300)
    AST = models.CharField(max_length=300)
    AST_status = models.CharField(max_length=300)
    ALT = models.CharField(max_length=300)
    ALT_status = models.CharField(max_length=300)
    age_two = models.CharField(max_length=300)
    duration_of_employment = models.CharField(max_length=300)
    overweight = models.CharField(max_length=300)